### ISSUE TITLE
Practica 3 Visual Studio UX UI

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos_a-4bs-idm#1]
PRACTICA 3: 
[Practica 3 Visual Studio UX UI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos_a-4bs-idm/files/14304670/Practica.3.Visual.Studio.UX.UI.pdf)

INTEGRANTES DE EQUIPO:
ROSAS GRACIA MARCO URIEL
CRUZ CRUZ DIEGO

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica de evaluación tienen un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
